# Generated by Django 3.2.7 on 2021-12-01 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_alter_patientprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '(123) 123 - 1234'. Up to 15 digits allowed.", regex='\\(\\d\\d\\d\\)\\ \\d\\d\\d\\ \\-\\ \\d\\d\\d\\d')]),
        ),
    ]
